-- ==============================================================================
-- GO FETCH, GIZMO! - SUPABASE COMPLETE DATABASE SCHEMA & RLS POLICIES
-- Run this script in the Supabase Dashboard -> SQL Editor
-- ==============================================================================

-- 1. CUSTOMERS TABLE (Customer 360, Gate Codes, Lifetime Value)
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'Neighbor',
    phone TEXT UNIQUE NOT NULL,
    email TEXT,
    address TEXT,
    zip_code TEXT,
    customer_type TEXT DEFAULT 'residential', -- 'residential', 'b2b_property_manager', 'b2b_realtor', 'repeat_vip'
    total_jobs INTEGER DEFAULT 0,
    total_revenue INTEGER DEFAULT 0,
    gate_code TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. LEADS / JOBS TABLE (Dispatch Pipeline: new -> quoted -> scheduled -> en_route -> completed)
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    name TEXT,
    phone TEXT NOT NULL,
    zip_code TEXT,
    address TEXT,
    status TEXT DEFAULT 'new', -- 'new', 'quoted', 'scheduled', 'en_route', 'completed'
    estimated_tier TEXT,      -- 'terrier', 'retriever', 'great_dane'
    estimated_price_min INTEGER DEFAULT 150,
    estimated_price_max INTEGER DEFAULT 180,
    final_price INTEGER,
    standby_opt_in BOOLEAN DEFAULT FALSE,
    special_notes TEXT,
    photos_json TEXT DEFAULT '[]',
    source TEXT DEFAULT 'web',
    preferred_date TEXT,
    scheduled_time TEXT,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SMS / MMS MESSAGES TABLE (2-Way Live Chat History)
CREATE TABLE IF NOT EXISTS public.sms_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT REFERENCES public.leads(id) ON DELETE SET NULL,
    phone_number TEXT NOT NULL,
    direction TEXT NOT NULL,   -- 'inbound', 'outbound'
    body TEXT,
    media_urls_json TEXT DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. REVIEW REQUESTS TABLE (5-Star Google Review Tracking & Bacon Treats)
CREATE TABLE IF NOT EXISTS public.review_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT REFERENCES public.leads(id) ON DELETE SET NULL,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    customer_name TEXT,
    phone_number TEXT NOT NULL,
    sent_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'sent',
    rating INTEGER DEFAULT 5,
    review_text TEXT
);

-- 5. B2B PROSPECTS TABLE (Sacramento Property Managers & Realtors)
CREATE TABLE IF NOT EXISTS public.b2b_prospects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    category TEXT DEFAULT 'Property Management', -- 'Property Management', 'Real Estate', 'Storage Facility'
    address TEXT,
    city TEXT DEFAULT 'Citrus Heights',
    status TEXT DEFAULT 'scouted',               -- 'scouted', 'emailed', 'meeting_set', 'partner'
    last_contacted_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. CLASSIFIED SIGNALS TABLE (Craigslist Curb Alerts, Landlord Vacancies & Moving Gigs)
CREATE TABLE IF NOT EXISTS public.classified_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cl_post_id TEXT UNIQUE NOT NULL,
    category TEXT NOT NULL, -- 'curb_alert', 'landlord_vacancy', 'hauling_gig'
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    location TEXT,
    snippet TEXT,
    suggested_pitch TEXT,
    status TEXT DEFAULT 'new', -- 'new', 'contacted', 'converted', 'dismissed'
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- INDEXES FOR ULTRA-FAST QUERY PERFORMANCE
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers (phone);
CREATE INDEX IF NOT EXISTS idx_leads_status ON public.leads (status);
CREATE INDEX IF NOT EXISTS idx_leads_customer_id ON public.leads (customer_id);
CREATE INDEX IF NOT EXISTS idx_sms_phone ON public.sms_messages (phone_number);
CREATE INDEX IF NOT EXISTS idx_b2b_status ON public.b2b_prospects (status);
CREATE INDEX IF NOT EXISTS idx_signals_cl_post_id ON public.classified_signals (cl_post_id);
CREATE INDEX IF NOT EXISTS idx_signals_category ON public.classified_signals (category);
CREATE INDEX IF NOT EXISTS idx_signals_status ON public.classified_signals (status);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sms_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.b2b_prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classified_signals ENABLE ROW LEVEL SECURITY;

-- 1. Anonymous Web Users can insert new bookings/quotes
CREATE POLICY "Public anonymous can insert leads" 
ON public.leads FOR INSERT 
TO anon, authenticated, service_role 
WITH CHECK (true);

-- 2. Authenticated Admin Users (Brandon) & Service Role have full access
CREATE POLICY "Authenticated admin full access customers" 
ON public.customers FOR ALL 
TO authenticated, service_role 
USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated admin full access leads" 
ON public.leads FOR ALL 
TO authenticated, service_role 
USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated admin full access sms" 
ON public.sms_messages FOR ALL 
TO authenticated, service_role 
USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated admin full access reviews" 
ON public.review_requests FOR ALL 
TO authenticated, service_role 
USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated admin full access b2b" 
ON public.b2b_prospects FOR ALL 
TO authenticated, service_role 
USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated admin full access signals" 
ON public.classified_signals FOR ALL 
TO authenticated, service_role 
USING (true) WITH CHECK (true);

-- ==============================================================================
-- INITIAL B2B SEED DATA (Citrus Heights / Sacramento Commercial Partners)
-- ==============================================================================
INSERT INTO public.b2b_prospects (company_name, contact_name, email, phone, category, city, status)
VALUES
    ('Sacramento Property Management Pros', 'Elena Rostova', 'elena@sacpremierprop.com', '(916) 555-0144', 'Property Management', 'Citrus Heights', 'scouted'),
    ('Lyon Real Estate - Citrus Heights Group', 'Mark Henderson', 'mhenderson@golyon.com', '(916) 555-0188', 'Real Estate', 'Citrus Heights', 'scouted'),
    ('Greenback Self Storage', 'Dave Clark', 'manager@greenbackstorage.com', '(916) 555-0122', 'Storage Facility', 'Citrus Heights', 'scouted'),
    ('River City Rentals & HOA', 'Amanda Cruz', 'amanda@rivercityrentals.com', '(916) 555-0199', 'Property Management', 'Carmichael', 'scouted'),
    ('Fair Oaks Village Realty', 'Tom Bennett', 'tom@fairoaksrealty.com', '(916) 555-0177', 'Real Estate', 'Fair Oaks', 'scouted')
ON CONFLICT DO NOTHING;
