name = "gofetchgizmo"
main = "src/index.js"
compatibility_date = "2024-09-01"

[assets]
directory = "./app"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"
BUSINESS_NAME = "Go Fetch, Gizmo!"
BUSINESS_PHONE = "(916) 546-8537"
GEMINI_API_KEY = ""
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
SUPABASE_SERVICE_ROLE_KEY = ""
